### ISSUE TITLE
Missing "type" field in SQLite storage runtime configuration

### ISSUE THREAD

**Issue by rylev** [fermyon/developer#1332]
In the docs on [SQLite storage runtime configuration](https://developer.fermyon.com/spin/v2/dynamic-configuration#sqlite-storage-runtime-configuration), the example toml is not correct and will result in an error if used.

Instead of this:

```toml
[sqlite_database.todo]
path = "/planning/todo.db"
```

It should be this:

```toml
[sqlite_database.todo]
type = "spin" # This is missing!
path = "/planning/todo.db"
```
